-- CreateEnum
CREATE TYPE "CohortType" AS ENUM ('SOFTWARE_DEVELOPMENT', 'FRONTEND_DEVELOPMENT', 'DATA_ANALYTICS');

-- AlterTable
ALTER TABLE "Cohort" ADD COLUMN     "type" "CohortType" NOT NULL DEFAULT E'SOFTWARE_DEVELOPMENT';
